// value is overridden dynamically in Dashboard.jsx using real Shopify order counts
export const STAT_CARDS = [
  {
    id: 'total',
    label: 'Total Orders',
    value: '—',
    change: null,
    changeType: null,
    icon: 'ShoppingBag',
    bgColor: '#eff6ff',
    iconColor: '#3b82f6',
  },
  {
    id: 'pending',
    label: 'Pending Orders',
    value: '—',
    change: null,
    changeType: null,
    icon: 'Clock',
    bgColor: '#fffbeb',
    iconColor: '#d97706',
  },
  {
    id: 'submitted',
    label: 'Submitted Orders',
    value: '—',
    change: null,
    changeType: null,
    icon: 'CheckCircle',
    bgColor: '#ecfdf5',
    iconColor: '#059669',
  },
  {
    id: 'failed',
    label: 'Failed Orders',
    value: '—',
    change: null,
    changeType: null,
    icon: 'XCircle',
    bgColor: '#fef2f2',
    iconColor: '#dc2626',
  },
]

export const RECENT_ORDERS = [
  {
    id: 'SU-1008',
    shopifyOrderId: '#5008',
    customer: { name: 'William Foster', email: 'w.foster@email.com', phone: '+44 7700 900890' },
    supplier: 'Milano Fabrics Ltd',
    items: '3-Piece Bespoke Suit',
    fabric: 'Super 130s Wool',
    color: 'Navy Blue',
    measurementsId: 'MTM-2408',
    orderDate: '2024-01-22',
    deliveryDate: '2024-02-22',
    total: '$1,849.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'submitted',
    tags: ['VIP'],
  },
  {
    id: 'SU-1007',
    shopifyOrderId: '#5007',
    customer: { name: 'Oliver Bennett', email: 'o.bennett@email.com', phone: '+44 7700 900789' },
    supplier: 'London Tailors Co.',
    items: '2-Piece Slim Fit',
    fabric: 'Merino Wool',
    color: 'Dark Charcoal',
    measurementsId: 'MTM-2407',
    orderDate: '2024-01-21',
    deliveryDate: '2024-02-18',
    total: '$985.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'pending',
    tags: [],
  },
  {
    id: 'SU-1006',
    shopifyOrderId: '#5006',
    customer: { name: 'Henry Clarke', email: 'h.clarke@email.com', phone: '+44 7700 900678' },
    supplier: 'Milano Fabrics Ltd',
    items: 'Tuxedo Suit',
    fabric: 'Wool & Mohair',
    color: 'Midnight Black',
    measurementsId: 'MTM-2406',
    orderDate: '2024-01-20',
    deliveryDate: '2024-02-10',
    total: '$2,150.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'failed',
    tags: ['Rush'],
  },
  {
    id: 'SU-1005',
    shopifyOrderId: '#5005',
    customer: { name: 'George Harrison', email: 'g.harrison@email.com', phone: '+44 7700 900567' },
    supplier: 'Napoli Casa',
    items: '2-Piece Classic Fit',
    fabric: 'Super 100s Wool',
    color: 'Light Grey',
    measurementsId: 'MTM-2405',
    orderDate: '2024-01-19',
    deliveryDate: '2024-02-20',
    total: '$1,120.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'submitted',
    tags: [],
  },
  {
    id: 'SU-1004',
    shopifyOrderId: '#5004',
    customer: { name: 'Edward Wilson', email: 'e.wilson@email.com', phone: '+44 7700 900456' },
    supplier: 'London Tailors Co.',
    items: 'Blazer Only',
    fabric: 'Linen Blend',
    color: 'Beige',
    measurementsId: 'MTM-2404',
    orderDate: '2024-01-18',
    deliveryDate: '2024-02-12',
    total: '$650.00',
    paymentStatus: 'unpaid',
    fulfillmentStatus: 'unfulfilled',
    status: 'pending',
    tags: [],
  },
  {
    id: 'SU-1003',
    shopifyOrderId: '#5003',
    customer: { name: 'Arthur Davies', email: 'a.davies@email.com', phone: '+44 7700 900345' },
    supplier: 'Napoli Casa',
    items: '3-Piece Suit',
    fabric: 'Super 120s Wool',
    color: 'Burgundy',
    measurementsId: 'MTM-2403',
    orderDate: '2024-01-17',
    deliveryDate: '2024-02-17',
    total: '$1,750.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'submitted',
    tags: ['VIP', 'Rush'],
  },
  {
    id: 'SU-1002',
    shopifyOrderId: '#5002',
    customer: { name: 'Charles Martin', email: 'c.martin@email.com', phone: '+44 7700 900234' },
    supplier: 'Milano Fabrics Ltd',
    items: '2-Piece Bespoke Suit',
    fabric: 'Cashmere Blend',
    color: 'Charcoal',
    measurementsId: 'MTM-2402',
    orderDate: '2024-01-16',
    deliveryDate: '2024-02-16',
    total: '$2,490.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    status: 'submitted',
    tags: ['VIP'],
  },
  {
    id: 'SU-1001',
    shopifyOrderId: '#5001',
    customer: { name: 'James Thornton', email: 'james.t@email.com', phone: '+44 7700 900123' },
    supplier: 'Milano Fabrics Ltd',
    items: '2-Piece Bespoke Suit',
    fabric: 'Super 120s Wool',
    color: 'Charcoal Grey',
    measurementsId: 'MTM-2401',
    orderDate: '2024-01-15',
    deliveryDate: '2024-02-15',
    total: '$1,249.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'submitted',
    tags: ['VIP', 'Rush'],
  },
]

export const ALL_ORDERS = [
  ...RECENT_ORDERS,
  {
    id: 'SU-1009',
    shopifyOrderId: '#5009',
    customer: { name: 'Thomas Wright', email: 't.wright@email.com', phone: '+44 7700 900901' },
    supplier: 'London Tailors Co.',
    items: '2-Piece Slim Fit',
    fabric: 'Super 120s Wool',
    color: 'Midnight Blue',
    measurementsId: 'MTM-2409',
    orderDate: '2024-01-23',
    deliveryDate: '2024-02-23',
    total: '$1,080.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'pending',
    tags: [],
  },
  {
    id: 'SU-1010',
    shopifyOrderId: '#5010',
    customer: { name: 'Frederick Hill', email: 'f.hill@email.com', phone: '+44 7700 900012' },
    supplier: 'Napoli Casa',
    items: 'Tuxedo Suit',
    fabric: 'Wool & Silk',
    color: 'Black',
    measurementsId: 'MTM-2410',
    orderDate: '2024-01-24',
    deliveryDate: '2024-02-24',
    total: '$2,350.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'submitted',
    tags: ['VIP'],
  },
  {
    id: 'SU-1011',
    shopifyOrderId: '#5011',
    customer: { name: 'Alexander Hunt', email: 'a.hunt@email.com', phone: '+44 7700 900111' },
    supplier: 'Milano Fabrics Ltd',
    items: '3-Piece Suit',
    fabric: 'Super 150s Wool',
    color: 'Dark Navy',
    measurementsId: 'MTM-2411',
    orderDate: '2024-01-25',
    deliveryDate: '2024-02-25',
    total: '$3,100.00',
    paymentStatus: 'unpaid',
    fulfillmentStatus: 'unfulfilled',
    status: 'failed',
    tags: [],
  },
  {
    id: 'SU-1012',
    shopifyOrderId: '#5012',
    customer: { name: 'Sebastian King', email: 's.king@email.com', phone: '+44 7700 900222' },
    supplier: 'London Tailors Co.',
    items: 'Blazer + Trouser',
    fabric: 'Tweed',
    color: 'Brown Herringbone',
    measurementsId: 'MTM-2412',
    orderDate: '2024-01-26',
    deliveryDate: '2024-02-28',
    total: '$890.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'pending',
    tags: ['Rush'],
  },
  {
    id: 'SU-1013',
    shopifyOrderId: '#5013',
    customer: { name: 'Nathaniel Stone', email: 'n.stone@email.com', phone: '+44 7700 900333' },
    supplier: 'Napoli Casa',
    items: '2-Piece Classic Fit',
    fabric: 'Super 100s Wool',
    color: 'Medium Grey',
    measurementsId: 'MTM-2413',
    orderDate: '2024-01-27',
    deliveryDate: '2024-03-01',
    total: '$1,050.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'fulfilled',
    status: 'submitted',
    tags: [],
  },
  {
    id: 'SU-1014',
    shopifyOrderId: '#5014',
    customer: { name: 'Maximilian Cross', email: 'm.cross@email.com', phone: '+44 7700 900444' },
    supplier: 'Milano Fabrics Ltd',
    items: '3-Piece Bespoke Suit',
    fabric: 'Super 130s Wool',
    color: 'Royal Blue',
    measurementsId: 'MTM-2414',
    orderDate: '2024-01-28',
    deliveryDate: '2024-03-02',
    total: '$2,200.00',
    paymentStatus: 'partial',
    fulfillmentStatus: 'unfulfilled',
    status: 'submitted',
    tags: ['VIP'],
  },
  {
    id: 'SU-1015',
    shopifyOrderId: '#5015',
    customer: { name: 'Benjamin Price', email: 'b.price@email.com', phone: '+44 7700 900555' },
    supplier: 'London Tailors Co.',
    items: 'Slim Fit Tuxedo',
    fabric: 'Mohair Blend',
    color: 'Jet Black',
    measurementsId: 'MTM-2415',
    orderDate: '2024-01-29',
    deliveryDate: '2024-03-03',
    total: '$1,680.00',
    paymentStatus: 'paid',
    fulfillmentStatus: 'unfulfilled',
    status: 'failed',
    tags: [],
  },
]

export const SUPPLIERS = [
  'All Suppliers',
  'Milano Fabrics Ltd',
  'London Tailors Co.',
  'Napoli Casa',
]
