export const STAT_CARDS = [
  {
    id: "pending",
    label: "Pending Orders",
    value: "—",
    change: null,
    changeType: null,
    icon: "Clock",
    bgColor: "#fffbeb",
    iconColor: "#d97706",
  },
  {
    id: "failed",
    label: "Failed Orders",
    value: "—",
    change: null,
    changeType: null,
    icon: "XCircle",
    bgColor: "#fef2f2",
    iconColor: "#dc2626",
  },
  {
    id: "verified",
    label: "Verified Supplier",
    value: "—",
    change: null,
    changeType: null,
    icon: "BadgeCheck",
    bgColor: "#f0fdf4",
    iconColor: "#16a34a",
  },
];
