export const STAT_CARDS = [
  {
    id: "total",
    label: "Total Orders",
    value: "—",
    change: null,
    changeType: null,
    icon: "ShoppingBag",
    bgColor: "#eff6ff",
    iconColor: "#3b82f6",
  },
  {
    id: "pending",
    label: "Pending Orders",
    value: "—",
    change: null,
    changeType: null,
    icon: "Clock",
    bgColor: "#fffbeb",
    iconColor: "#d97706",
  },
  {
    id: "submitted",
    label: "Submitted Orders",
    value: "—",
    change: null,
    changeType: null,
    icon: "CheckCircle",
    bgColor: "#ecfdf5",
    iconColor: "#059669",
  },
  {
    id: "failed",
    label: "Failed Orders",
    value: "—",
    change: null,
    changeType: null,
    icon: "XCircle",
    bgColor: "#fef2f2",
    iconColor: "#dc2626",
  },
];
